name: Trigger fuzzing CI
on:
  push:
    branches: [ testing_framework ]

jobs:
  Exec-fuzzer:
    runs-on: self-hosted

    steps:
      - name: Triggered by
        run: echo "Submitted by ${{ github.actor }}"

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Copy Keys
        run: cp -rp ~ubuntu/TestCode/keystore .github/misc/fuzzing/TestCode >/dev/null 2>&1

      - name: Copy Keys bla
        run: cp -rp ~ubuntu/bla .github/misc/fuzzing/TestCode
