name: Trigger fuzzing CI
on:
  push:
    branches: [ testing_framework ]

jobs:
  Exec-fuzzer:
    runs-on: self-hosted

    steps:
      - name: Job submitted by
        run: echo "Submitted by ${{ github.actor }}"

      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Copy Keys
        run: cp -rp ~ubuntu/TestCode/keystore .github/misc/fuzzing/TestCode

      - name: Execute abi
        run: docker run -v /home/ubuntu/actions-runner/_work/zkevm-chain/zkevm-chain/contracts:/sources ethereum/solc:stable --abi /sources/ZkEvmL1Bridge.sol -o /sources/build

      - name: Create l1bridge directory
        run: mkdir .github/misc/fuzzing/TestCode/l1bridge

      - name: Copy abi
        run: cp contracts/build/ZkEvmL1Bridge.abi .github/misc/fuzzing/TestCode/l1bridge

      - name: Prepare go environment
        run: docker-compose -f .github/misc/fuzzing/docker/docker-compose.action.yml --profile preparego up

      - name: Run tests
        run: docker-compose -f .github/misc/fuzzing/docker/docker-compose.action.yml --profile executego up

      - name: Fix permissions
        run: find . ! -user ubuntu -exec sudo chown ubuntu.ubuntu {} \;
